export enum RouteNames {
  WELCOME = "/welcome",
  REGISTER = "/register",
  REG_TYPE_ACCOUNT = "reg-type-account",
  REG_CREATE_ACCOUNT = "create-account",
  LOGIN = "/login",
  HOME = "/",
  ADS = "/ads",
  USER = "/user",
  CHANGE_PROFILE = "change-profile",
  OTHER_PROFILE_USER = "/other-user-profile",
  SETTINGS = "settings",
  CHATS = "/chats",
  NOTIFICATION = "/notification",
  RECOVERY_PASSWORD = "/recovery-password",
  RECOVERY_CREATE_PASSWORD = "recovery-create-password",
}
