export const exportIconsSVG: any = {
 //  DJ
 DJ: require("./DJ.svg").default,
 // Духовые
 bassoon: require("./bassoon.svg").default,
 harmonica: require("./harmonica.svg").default,
 tuba: require("./tuba.svg").default,
 bagpipes: require("./bagpipes.svg").default,
 horn: require("./horn.svg").default,
 clarinet: require("./clarinet.svg").default,
 trombone: require("./trombone.svg").default,
 oboe: require("./oboe.svg").default,
 saxophone: require("./saxophone.svg").default,
 trumpet: require("./trumpet.svg").default,
 flute: require("./flute.svg").default,
 // Вокал
 soprano: require("./vocals.svg").default,
 "mezzo-soprano": require("./vocals.svg").default,
 baritone: require("./vocals.svg").default,
 contralto: require("./vocals.svg").default,
 bass: require("./vocals.svg").default,
 tenor: require("./vocals.svg").default,
 // Струнные
 mandolin: require("./mandolin.svg").default,
 electric_guitar: require("./electric_guitar.svg").default,
 classical_guitar: require("./classical_guitar.svg").default,
 bass_guitar: require("./bass_guitar.svg").default,
 banjo: require("./banjo.svg").default,
 balalaika: require("./balalaika.svg").default,
 harp: require("./harp.svg").default,
 acoustic_guitar: require("./acoustic_guitar.svg").default,
 ukulele: require("./ukulele.svg").default,
 // Клавишные
 synthesizer: require("./synthesizer.svg").default,
 accordion: require("./accordion.svg").default,
 harmonic: require("./harmonic.svg").default,
 button_accordion: require("./button_accordion.svg").default,
 organ: require("./organ.svg").default,
 piano: require("./piano.svg").default, //
 // Смычково-струнные
 double_bass: require("./double_bass.svg").default,
 violin: require("./violin.svg").default,
 alto: require("./alto.svg").default,
 cello: require("./cello.svg").default,
 // Ударные
 timpani: require("./timpani.svg").default,
 conga: require("./conga.svg").default,
 tambourine: require("./tambourine.svg").default,
 drum_set: require("./drum_set.svg").default,
 djembe: require("./djembe.svg").default,
 cymbal: require("./cymbal.svg").default,
 xylophone: require("./xylophone.svg").default,
 drum_big: require("./drum_big.svg").default,
 maracas: require("./maracas.svg").default,
 bell: require("./bell.svg").default,
 gong: require("./gong.svg").default,
 drum_small: require("./drum_small.svg").default,
 bongo: require("./bongo.svg").default,
 triangle: require("./triangle.svg").default,
};

export default exportIconsSVG;
